version: '3.7'

services:
  glue-instance:
    image: amazon/aws-glue-libs:glue_libs_4.0.0_image_01
    command: -c "/home/glue_user/jupyter/jupyter_start.sh"
    environment:
      AWS_ACCESS_KEY_ID: ${S3_ACCESS_KEY:-}
      AWS_SECRET_ACCESS_KEY: ${S3_SECRET_KEY:-}
      AWS_REGION: local
      AWS_S3_ENDPOINT: http://host.docker.internal:9000
      DISABLE_SSL: true
    ports:
      - "18080:18080"
      - "4040:4040"
      - "8998:8998"
      - "8888:8888"
    volumes:
      - type: bind
        source: workspace
        target: /home/glue_user/workspace/jupyter_workspace
      - type: bind
        source: ../../spark-applications
        target: /home/glue_user/jobs
        read_only: true
