version: '3.7'

services:
  s3-storage:
    image: minio/minio:RELEASE.2024-02-17T01-15-57Z.fips
    command: server /data
    environment:
      MINIO_ACCESS_KEY: ${S3_ACCESS_KEY:-}
      MINIO_SECRET_KEY: ${S3_SECRET_KEY:-}
    ports:
      - "9000:9000"
