version: '3.7'

services:
  spark-master:
    image: bitnami/spark:3.4-debian-11
    command: bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "7077:7077"
      - "9090:8080"
    volumes:
      - type: bind
        source: ../../spark-applications
        target: /opt/bitnami/spark/apps
        read_only: true

  spark-worker-1:
    image: bitnami/spark:3.4-debian-11
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 2g
      SPARK_MASTER_URL: spark://spark-master:7077
