#Pass respective values through environment variables

client-azureopenai-key: ${AZURE_OPEN_AI_KEY}
client-azureopenai-endpoint: ${AZURE_OPEN_AI_ENDPOINT}
client-azureopenai-deployment-name: ${AZURE_OPEN_AI_DEPLOYMENT_NAME}

epam:
  dial:
    deployment-names-api: https://ai-proxy.lab.epam.com/openai/deployments

vector:
  collection:
    name: app_embeddings
model:
  embedding:
    name: text-embedding-ada-002
    limit: 5
qdrant:
  host: localhost
  port: 6334
  useTls: false
prompt-execution-settings:
  temperature: 0.5
  max-tokens: 100
  stop-sequences:
  model-id: gpt-4o-2024-05-13
