version: '3.7'

services:
  grafana:
    image: grafana/grafana-oss:10.2.5
    environment:
      GF_INSTALL_PLUGINS: "grafana-athena-datasource 2.13.5"
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: .aws
        target: /usr/share/grafana/.aws
